version: 2

release:
  mode: replace

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - formats: [ 'zip' ]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

dockers:
  - image_templates:
      - "ghcr.io/jo-m/podfather:{{ .Version }}-amd64"
      - "ghcr.io/jo-m/podfather:latest-amd64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
    goarch: amd64
    dockerfile: Dockerfile
  - image_templates:
      - "ghcr.io/jo-m/podfather:{{ .Version }}-arm64"
      - "ghcr.io/jo-m/podfather:latest-arm64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
    goarch: arm64
    dockerfile: Dockerfile

docker_manifests:
  - name_template: "ghcr.io/jo-m/podfather:{{ .Version }}"
    image_templates:
      - "ghcr.io/jo-m/podfather:{{ .Version }}-amd64"
      - "ghcr.io/jo-m/podfather:{{ .Version }}-arm64"
  - name_template: "ghcr.io/jo-m/podfather:latest"
    image_templates:
      - "ghcr.io/jo-m/podfather:latest-amd64"
      - "ghcr.io/jo-m/podfather:latest-arm64"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
