version: 2

release:
  mode: replace

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - formats: [ 'zip' ]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

dockers_v2:
  - images:
      - "ghcr.io/jo-m/podfather"
    tags:
      - "{{ .Version }}"
      - "latest"
    dockerfile: Dockerfile

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
