version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

dockers:
  - image_templates:
      - "ghcr.io/jo-m/podview:{{ .Version }}-amd64"
      - "ghcr.io/jo-m/podview:latest-amd64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
    goarch: amd64
    dockerfile: Dockerfile
  - image_templates:
      - "ghcr.io/jo-m/podview:{{ .Version }}-arm64"
      - "ghcr.io/jo-m/podview:latest-arm64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
    goarch: arm64
    dockerfile: Dockerfile

docker_manifests:
  - name_template: "ghcr.io/jo-m/podview:{{ .Version }}"
    image_templates:
      - "ghcr.io/jo-m/podview:{{ .Version }}-amd64"
      - "ghcr.io/jo-m/podview:{{ .Version }}-arm64"
  - name_template: "ghcr.io/jo-m/podview:latest"
    image_templates:
      - "ghcr.io/jo-m/podview:latest-amd64"
      - "ghcr.io/jo-m/podview:latest-arm64"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
